import { CodeChange } from '../types/index.js';

/**
 * Parameters for generating a pull request description
 */
interface PRDescriptionParams {
  issueNumber: number;
  changes: CodeChange[];
  analysis: string;
}

/**
 * Generates a formatted pull request description including the analysis
 * and a list of changes made.
 */
export function generatePRDescription({ issueNumber, changes, analysis }: PRDescriptionParams): string {
  return `
## 🤖 AI-Generated Pull Request

This PR was automatically generated in response to issue #${issueNumber}.

### 📝 Analysis
${analysis}

### 🔄 Changes Made
${changes.map(change => `
* \`${change.path}\`: ${change.message}`).join('\n')}

---
Generated by Axiotree Langchain AI PR Bot 🌲
Use \`/ai-issue-resolver-change\` followed by your request to suggest changes.
`;
}